solution
AntonGorodetsky/ObodevSandbox pull request #1
Opened 2023-01-29 15:22 UTC by AntonGorodetsky

Is this right?

2023-01-29 15:23 UTC, obozhdi requested changes

2023-01-29 15:23 UTC, obozhdi commented on getProperTime.playground/Contents.swift
> +  return
Odd return

2023-01-29 15:23 UTC, obozhdi commented on getProperTime.playground/Contents.swift
> +func getProperTime(seconds: Int) -> String {
Still too complex solution

2023-01-29 15:48 UTC, AntonGorodetsky commented on getProperTime.playground/Contents.swift
> +func getProperTime(seconds: Int) -> String {
is it too complex because of the "import Foundation"?

2023-01-29 15:51 UTC, obozhdi commented on getProperTime.playground/Contents.swift
> +func getProperTime(seconds: Int) -> String {
it is too complex cuz u do a lot of unnecessary actions

2023-01-29 16:34 UTC, obozhdi requested changes
Code has no changes, what am I to review?

2023-01-31 07:42 UTC, obozhdi requested changes

2023-01-31 07:42 UTC, obozhdi commented on getProperTime.playground/Contents.swift
> +}
Too complex

2023-01-31 15:34 UTC, obozhdi approved these changes

2023-01-31 15:34 UTC, merged